### ISSUE TITLE
npm install @wasm-tool/rollup-plugin-rust does not work on Apple Silicon (M1)

### ISSUE THREAD

**Issue by GoldStrikeArch** [wasm-tool/rollup-plugin-rust#24]
Errors log afte running ```npm install @wasm-tool/rollup-plugin-rust```

```npm ERR!   throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!   ^
npm ERR! 
npm ERR! Error: Unsupported platform: Darwin arm64```

**Comment by GoldStrikeArch** [comment]
Update:

Here is a more detailed look about it: https://github.com/rust-lang/rust/issues/90342#issuecomment-961828276

**Comment by Pauan** [comment]
That sounds like a bug in wasm-pack, so it should be reported here:

https://github.com/rustwasm/wasm-pack/issues

**Comment by human-bean-555** [comment]
@MihailPertsev if you run `npm install @wasm-tool/rollup-plugin-rust --ignore-scripts` it will work. You will need to make sure you have installed `wasm-pack` locally using `cargo install wasm-pack`.

@Pauan I'm not even sure that this package needs a dependency on the `wasm-pack` npm package? Isn't it calling the local cargo installation anyway, rather than the binary in the `node_modules/.bin` folder?

**Comment by GoldStrikeArch** [comment]
> @MihailPertsev if you run `npm install @wasm-tool/rollup-plugin-rust --ignore-scripts` it will work. You will need to make sure you have installed `wasm-pack` locally using `cargo install wasm-pack`.
> 

Yes, with this additional ```--ignore-scripts``` flag everything is fine. It is a pain that you have to manually install a local version of ```wasm-pack``` beforehand though...

**Comment by Pauan** [comment]
> @pauldorehill I'm not even sure that this package needs a dependency on the wasm-pack npm package? Isn't it calling the local cargo installation anyway, rather than the binary in the node_modules/.bin folder?

Not at all, it is using the local `node_modules` package. Which is how it should be, because that ensures reproducibility. Global packages are really bad.

**Comment by human-bean-555** [comment]
Ah indeed.. showing my lack of node understanding 😄 . I hadn't realized that node would look in `node_modules/.bin' when spawning a child process.

**Comment by Pauan** [comment]
To clarify, if you are using this plugin, then you do not need a global installation of wasm-pack, *everything* is automatically managed by the plugin without any fuss. Everything Just Works™, including version locking.

The only time you would need to use the global installation of wasm-pack is because you want to use a custom build of wasm-pack.

**Comment by Pauan** [comment]
In version 2.0.0 we no longer use wasm-pack. Please try upgrading and then let me know if you're still having the same issue.

**Comment by human-bean-555** [comment]
Version 2 works seamlessly on mac

**Comment by Pauan** [comment]
@pauldorehill Thanks for letting me know, so I'll consider this issue as fixed.
