### ISSUE TITLE
Emit async module with top-level-await for init()

### ISSUE THREAD

**Issue by JanKaul** [wasm-tool/rollup-plugin-rust#31]
Do you think it is a good idea to create an async module in which the init() method is awaited for. The consumer must be able to handle the top-level-await statement. But since all major browsers and node support it, it hides the asynchronous instantiation of the wasm module from the user.

The output looks something like this:

```
export * from ${import_path};
import init from ${import_path};
    
await init(${import_wasm}).catch(console.error);
```

I have created a [branch](https://github.com/JanKaul/rollup-plugin-rust/tree/async_esmodule) where I implemented a `topLevelAwait: boolean` option for the rollup-plugin-rust that activates this behavior.

**Comment by Pauan** [comment]
Unfortunately top-level await is experimental and [still not supported by Rollup](https://github.com/rollup/rollup/issues/3623).

However, it's quite easy for the end-user to use top-level await if they wish:

```js
import wasm from "./path/to/Cargo.toml";

const exports = await wasm();
```

Then it is up to the user to make sure that top-level await is supported.

This also has the advantage that the user doesn't *need* to use top-level await, they have the choice.

And it allows them to [customize the loading behavior](https://github.com/wasm-tool/rollup-plugin-rust#customizing-the-import-url) with things like `serverPath` and `importHook`.

**Comment by JanKaul** [comment]
That makes total sense. I wanted to have something which hides the asynchronous complexity from the user and this option allowed me to do that. If you choose the output format "es" then top level await is supported in rollup.

**Comment by Pauan** [comment]
In the long term the goal is to have Wasm completely integrated with ES6 modules, so the user can do this:

```js
import { foo, bar } from "./path/to/Cargo.toml";
```

However, that will require more than top-level await, it requires [ESM integration](https://github.com/WebAssembly/esm-integration).

So in the meantime, I don't think there's much benefit to making any changes right now, since the only thing it does is remove the `const exports = await wasm();` line, but it also removes the ability to customize the file loading.

> If you choose the output format "es" then top level await is supported in rollup.

Right, because in that case Rollup is just relying on the browser's native top-level await, so [it won't work in older browsers](https://caniuse.com/mdn-javascript_operators_await_top_level).

**Comment by JanKaul** [comment]
All right, thanks for the clarification. I can't wait to get seamless integration.

**Comment by Pauan** [comment]
Version 2.3.0 now has an `experimental.directExports` option which enables top-level await.

Because this generates a top-level `await` in the code, it requires you to set the Rollup `format` to "es" or "system".
