### ISSUE TITLE
Failed to parse URL from assets

### ISSUE THREAD

**Issue by akitaSummer** [wasm-tool/rollup-plugin-rust#43]
Hello, I am developing a library using our plugin. I found that if I don't enable `inlineWasm`, it will be reported: 
```
 Failed to parse URL from assets/gm_crypto_wasm-e67215c8.wasm
```

This is my warehouse address:
https://github.com/akitaSummer/gm-crypto/tree/feat/add_wasm

You can run：
```
npm run build:rollup

npm run test:ava
```

Can my wasm only be loaded asynchronously? I have some hopes that it can be loaded synchronously. Also, can our plugin directly load the wasm product generated by `wasm-bindgen` instead of loading `cargo.toml`?

Thank you very much for taking the time to review my question.

**Comment by Pauan** [comment]
You need to set the `serverPath` to match the URL of your server:

```js
plugins: [
    rust({
        serverPath: "foo/bar/",
    }),
]
```

Replace `foo/bar/` with whatever the path is on your server.

> Can my wasm only be loaded asynchronously? I have some hopes that it can be loaded synchronously.

It can only be loaded asynchronously, this is a limitation of the browser.

> Also, can our plugin directly load the wasm product generated by wasm-bindgen instead of loading cargo.toml?

No, this plugin handles all of the compilation (including wasm-bindgen) itself. You shouldn't need to run wasm-bindgen yourself.

**Comment by akitaSummer** [comment]
Thank you very much for your answer, but I want to make a library. The `serverPath` field should not be determined by me, and it should be solved by the bundler.Is my understanding correct?

**Comment by Pauan** [comment]
Libraries are tricky because of bundling, you cannot control what bundler your users will use.

Different bundlers will put the Wasm file into different locations, and users will be putting the Wasm into different server paths.

There is an `importHook` function that you can use to determine the import path at runtime:

https://github.com/wasm-tool/rollup-plugin-rust#customizing-the-import-url

```js
import wasm from "./path/to/Cargo.toml";

let promise = null;

export default async function () {
    // Only load the Wasm a single time
    if (promise === null) {
        promise = wasm({
            importHook: () => {
                return new URL("foo.wasm", import.meta.url);
            },
        });
    }

    return await promise;
}
```

In order for this to work, you will need to change the `assetFileNames` in your Rollup config so that it doesn't do any hashing of the Wasm filename:

```js
output: {
    dir: "dist",
    format: "es",
    sourcemap: true,
    assetFileNames: "[name][extname]",
},
```

Most bundlers recognize the special `new URL` pattern, so this will work in most bundlers.

If your users use Rollup, then they must use [a Rollup plugin](https://www.npmjs.com/package/@web/rollup-plugin-import-meta-assets) to make it work.

**Comment by Pauan** [comment]
Also, most bundlers nowadays support top level await, so you can use this pattern instead:

```js
import wasm from "./path/to/Cargo.toml";

const { foo, bar } = await wasm({
    importHook: () => {
        return new URL("foo.wasm", import.meta.url);
    },
});

export { foo, bar };
```

This is a good way to create a library for Rust Wasm.

**Comment by akitaSummer** [comment]
Thank you, I will rethink how to design this library. I have tried using top level await, it only supports esm packaged products, and umd will report an error when packaging. I tried to use `rollup-plugin-tla` (https://github.com/lisonge/rollup-plugin-tla) to solve the problem, but it seems that this library does not support commonjs, causing me to report an error when running ava tests.This is so frustrating for me. I really hope to reduce the mental burden on my users, but it is a bit difficult at the moment.

**Comment by Pauan** [comment]
> I have tried using top level await, it only supports esm packaged products, and umd will report an error when packaging

All libraries should publish ES6 code. UMD is outdated and inefficient. Some bundlers no longer support UMD.

It is the responsibility of the user to compile the ES6 code to UMD (if they wish to do so), it is not the responsibility of the library.

> but it seems that this library does not support commonjs, causing me to report an error when running ava tests.This is so frustrating for me.

You should not need to use CommonJS modules. Modern unit test frameworks ([including Ava](https://github.com/avajs/ava/blob/main/docs/recipes/es-modules.md)) support ES6 modules.

Things like UMD or CommonJS are very old and are not used anymore with modern JavaScript development.

It is standard and normal to use ES6 modules. ES6 modules are natively supported in the browser, and they are natively supported in NodeJS. Top level await is also natively supported in the browser, and natively supported in NodeJS.

**Comment by akitaSummer** [comment]
Yes, you are right, I also really want everyone to use the es6 version of the code, I really should think about whether I should build the umd and commonjs version of the code.

**Comment by Pauan** [comment]
It is completely impossible to use top level await with UMD / CommonJS, because they do not support asynchronous modules.

So if you want to support UMD / CommonJS then you must use the async code which [I showed before](https://github.com/wasm-tool/rollup-plugin-rust/issues/43#issuecomment-1773848978).

Which means that your users will need to import your library like this:

```js
const initialize = require("your-library");

async function main() {
    const { foo, bar } = await initialize();

    // Use the exports from your library...
    foo();
    bar();
}

main();
```

This is a bad user experience, compared to using ES6 modules:

```js
import { foo, bar } from "your-library";

// Use the exports from your library...
foo();
bar();
```

Many npm packages nowadays only support ES6 modules. For example [chalk](https://www.npmjs.com/package/chalk) is ES6-only, they no longer provide a CommonJS version.

So I think it's fine if your library decides to only support ES6 modules.
