### ISSUE TITLE
Content hash of wasm file

### ISSUE THREAD

**Issue by tiffany352** [wasm-tool/rollup-plugin-rust#8]
I'm not sure if this is something that would be on this plugin's end, but it would be nice if the wasm file could include a hash like JS bundles do. That way, I can tell the cilent / service worker to aggressively cache everything.

For example, my `client.js` turns into `client.e9154435.js`, but my `rink-js.wasm` stays `rink-js.wasm`.

**Comment by Pauan** [comment]
@tiffany352 How are you generating the hash for the filename?

**Comment by Pauan** [comment]
Well, it turns out Rollup already supports hashes via the [`output.assetFileNames`](https://rollupjs.org/guide/en/#outputassetfilenames) option.

I just released version 1.0.5 which uses `output.assetFileNames` by default (unless you specify the `outDir` option), which means the `.wasm` file will be hashed by default.
