### ISSUE TITLE
Unclear how to use with TypeScript

### ISSUE THREAD

**Issue by shepmaster** [wasm-tool/rollup-plugin-rust#9]
**package.json**

```json
{
  "name": "demo",
  "version": "0.1.0",
  "main": "index.ts",
  "license": "MIT",
  "scripts": {
    "build": "rollup -c rollup.config.js",
    "watch": "rollup -c rollup.config.js --watch"
  },
  "devDependencies": {
    "@rollup/plugin-typescript": "^5.0.2",
    "@wasm-tool/rollup-plugin-rust": "^1.0.5",
    "rollup": "^2.23.0",
    "tslib": "^2.0.0",
    "typescript": "^3.9.7"
  }
}
```

**rollup.config.js**

```js
import typescript from '@rollup/plugin-typescript';
import rust from '@wasm-tool/rollup-plugin-rust';

const config = {
  input: 'index.js',
  output: {
    file: 'dist/demo.js',
    format: 'iife',
  },
  plugins: [
    rust(),
    typescript(),
  ],
};

export default config;
```

**index.ts**

```ts
import demo from './bindings/Cargo.toml';

async function loadWasm() {
    const exports = await demo();

    exports.greet("wow");
}

loadWasm();
```

**bindings/Cargo.toml**

```toml
[package]
name = "bindings"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
```

**bindings/src/lib.rs**

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    alert(&format!("Hello, {}!", name));
}
```

---

Running rollup causes this error:

```
% yarn build
yarn run v1.22.4
$ rollup -c rollup.config.js

index.js → dist/demo.js...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2307: Cannot find module './bindings/Cargo.toml' or its corresponding type declarations.
index.ts (1:20)

1 import demo from './bindings/Cargo.toml';
                   ~~~~~~~~~~~~~~~~~~~~~~~

Error: @rollup/plugin-typescript TS2307: Cannot find module './bindings/Cargo.toml' or its corresponding type declarations.
    at error (project/node_modules/rollup/dist/shared/rollup.js:5174:30)
    at throwPluginError (project/node_modules/rollup/dist/shared/rollup.js:17452:12)
    at Object.error (project/node_modules/rollup/dist/shared/rollup.js:18071:24)
    at emitDiagnostic (project/node_modules/@rollup/plugin-typescript/dist/index.js:415:17)
    at reportDiagnostics (project/node_modules/@rollup/plugin-typescript/dist/index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (project/node_modules/typescript/lib/typescript.js:105333:21)
    at Object.result.afterProgramCreate (project/node_modules/typescript/lib/typescript.js:105503:13)
    at Object.afterProgramCreate (project/node_modules/@rollup/plugin-typescript/dist/index.js:515:29)
    at synchronizeProgram (project/node_modules/typescript/lib/typescript.js:105767:22)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I rename the file from `index.ts` to `index.js` and update `rollup.config.js`, then I see that the Rust code is built, including the TypeScript types:

```
% find target -name '*.ts'
target/wasm-pack/bindings/index.d.ts
target/wasm-pack/bindings/index_bg.d.ts
```

**Comment by Pauan** [comment]
This is tricky to solve, because Rollup plugins can only return a single file, so it can't return both a `.js` and `.d.ts` file.

**Comment by Pauan** [comment]
Okay, so it's actually much worse than I thought: *none* of the Rollup transform plugins work with TypeScript, because TypeScript uses its own resolver.

Normally when you do `import demo from './bindings/Cargo.toml';` it will use Rollup's resolver to find the file `./bindings/Cargo.toml` (and it will then run the Rust plugin).

But TypeScript has its own resolver which is used instead of Rollup's resolver, so TypeScript has no idea what to do with the `Cargo.toml` file, so the Rust plugin is never run.

This affects *all* Rollup plugins, including `@rollup/plugin-json`, so this isn't something I can fix. Instead it needs to be fixed within `@rollup/plugin-typescript`.

The way to workaround this is to create a `bindings/Cargo.toml.d.ts` file which contains this:

```ts
type Exports = typeof import("../target/wasm-pack/bindings/index");
declare const exports: () => Promise<Exports>;
export default exports;
```

Now TypeScript can resolve the `Cargo.toml` file, and afterwards it gets passed to Rollup (which then passes it to the Rust plugin). Unfortunately this plugin cannot automate that, since `.d.ts` needs to be a real file that exists before Rollup is run.

Also, `@rollup/plugin-typescript` seems broken in various ways, so I recommend using [`rollup-plugin-typescript2`](https://www.npmjs.com/package/rollup-plugin-typescript2) instead.

**Comment by Pauan** [comment]
Another alternative is to use the `// @ts-ignore` magical comment to disable type checking for the import, like this:

```ts
// @ts-ignore
import demo from './bindings/Cargo.toml';
```

The `// @ts-ignore` comment only disables type checking on the next line, not the whole file.

This fixes the error, but now `demo` won't have proper type checking (it will have type `any`), so creating a `bindings/Cargo.toml.d.ts` file is better (since it has correct static typing).

**Comment by shepmaster** [comment]
Thank you for the very thorough response!

**Comment by shepmaster** [comment]
It does seem to fail sporadically, however:

```
index.ts → dist/strata.js...
   Compiling bindings v0.1.0 (project/bindings)
project/node_modules/rollup/dist/shared/rollup.js:5175 bindings
    throw base;
    ^

Error: @rollup/plugin-typescript TS6053: File 'project/target/wasm-pack/bindings/index.d.ts' not found.
```

A subsequent run, without changing any code, did work.

**Comment by Pauan** [comment]
@shepmaster Yes, that's because it must run the Rust plugin in order to generate the `target/wasm-pack/bindings/index.d.ts` file (which is imported by `Cargo.toml.d.ts`). And since the TypeScript plugin runs before the Rust plugin, it is necessary to run Rollup twice. But from the 2nd compilation onwards it will be fine.

**Comment by shepmaster** [comment]
> The way to workaround this is to create a `bindings/Cargo.toml.d.ts` file which contains this:
> 
> ```ts
> type Exports = typeof import("../target/wasm-pack/bindings/index");
> declare const exports: () => Promise<Exports>;
> export default exports;
> ```

This doesn't export any of the types from the `../target/wasm-pack/bindings/index.d.ts`, which means I can't do something like:

```ts
type IndexedSource = typeof import('path/to/Cargo.toml').IndexedSource;
```

I changed it to 

```ts
export * from "../target/wasm-pack/bindings/index";

type Exports = typeof import("../target/wasm-pack/bindings/index");
declare const init: () => Promise<Exports>;
export default init;
```

This worked fine until I cleaned my directory, then I realized that this will fail because the real file doesn't exist yet.

What I'm going to try next is having a specific task to generate it for me:

```
yarn rollup -c rollup-bootstrap.config.js > /dev/null
```

```js
import rust from "@wasm-tool/rollup-plugin-rust";

export default {
    input: {
        dummy: "./bindings/Cargo.toml",
    },
    plugins: [
        rust(),
    ],
};
```

**Comment by Porges** [comment]
Using the `.d.ts` from the previous answer worked nicely for me, thanks @shepmaster.

I also didn’t need to pre-build the Rust outputs, just having the `rust` plugin first is enough to do this. If you do see sporadic "`could not find index.d.ts`" errors when building then make sure your `tsconfig.json` excludes the Rust `target` directory or it will try to read the `.ts` files in there and there seems to be some kind of race around when they are deleted/recreated.

Here’s my minimal `rollup.config.js` in case that helps anyone else trying to figure this out (note I’m using module output, you might not want to):

```js
import rust from '@wasm-tool/rollup-plugin-rust';
import typescript from '@rollup/plugin-typescript';

/** @type {import('rollup').RollupOptions} */
const options = {
    input: {
        bundle: 'js/index.ts',
    },
    output: {
        dir: 'dist',
        format: 'es',
    },
    plugins: [
        rust(),
        typescript(),
    ],
};

export default options;
```

And `tsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "ES6",
        "strict": true,
        "noEmitOnError": true,
   },
   "exclude": [
       "target/**",
       "rollup.config.js",
   ]
}
```
